---
- name: Fetch metrics from hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Get hostname
      shell: hostname
      register: hostname
      failed_when: hostname.stdout == ""

    - name: Print CPU usage
      debug:
        msg: "CPU Usage: {{ cpu_usage.stdout }}"

    - name: Print Memory usage
      debug:
        msg: "Memory Usage: {{ memory_usage.stdout }}"

    - name: Print Disk usage
      debug:
        msg: "Disk Usage: {{ disk_usage.stdout }}"

    - name: Print Auth errors
      debug:
        msg: "Auth Errors: {{ auth_errors.stdout }}"


      - name: Combine metrics
        set_fact:
          metrics:
            hostname: "{{ hostname.stdout | default('Unknown') }}"
            datetime: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
            ip: "{{ ansible_default_ipv4.address | default('Unknown') }}"
            os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
            kernel: "{{ ansible_kernel }}"
            cpu_load: "{{ cpu_usage.stdout | default('0.0') }}"
            memory: "{{ memory_usage.stdout | default('0.0') }}"
            disk: "{{ disk_usage.stdout | default('0%') }}"
            auth_errors: "{{ auth_errors.stdout | default('0') }}"
        delegate_to: localhost

