---
- name: Fetch metrics from hosts
  hosts: all
  gather_facts: true
  tasks:
    - name: Get hostname
      shell: hostname
      register: hostname

    - name: Get CPU usage
      shell: top -bn1 | grep "Cpu(s)" | awk '{print $2 + $4}'
      register: cpu_usage

    - name: Get memory usage
      shell: free | grep Mem | awk '{print $3/$2 * 100.0}'
      register: memory_usage

    - name: Get disk usage
      shell: df -h / | grep / | awk '{print $5}'
      register: disk_usage

    - name: Get auth errors
      shell: grep "Failed password" /var/log/auth.log | wc -l
      register: auth_errors

    - name: Combine metrics
      set_fact:
        metrics:
          hostname: "{{ hostname.stdout }}"
          datetime: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
          ip: "{{ ansible_default_ipv4.address }}"
          os: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
          kernel: "{{ ansible_kernel }}"
          cpu_load: "{{ cpu_usage.stdout }}"
          memory: "{{ memory_usage.stdout }}"
          disk: "{{ disk_usage.stdout }}"
          auth_errors: "{{ auth_errors.stdout }}"
      delegate_to: localhost
