---
- name: Prepare Linux server for monitoring script
  hosts: all
  become: true
  tasks:

    # Обновление списка пакетов
    - name: Update the package list
      apt:
        update_cache: yes
      tags: update

    # Установка Python 3 и необходимых системных инструментов
    - name: Install Python 3 and required tools
      apt:
        name:
          - python3
          - python3-pip
          - software-properties-common
          - curl
        state: present
      tags: python

    # Установка Ansible
    - name: Ensure Ansible is installed
      apt:
        name: ansible
        state: present
      tags: ansible

    # Установка Python-зависимостей
    - name: Install Python dependencies
      shell: pip3 install ansible-runner flask prometheus_client psutil
      args:
        warn: false
        executable: /bin/bash
